### PR TITLE
Added a support for GraalVM native-image.

### PR DESCRIPTION
**Pull request by tzezula**
Added a support for the GraalVM `native-image` into the FnProject `cli`.

The `SVMLangHelper` creates a FnProject Java Maven Project which is extended by a maven profile doing the native image build. It uses its own `Dockerimage`s for building and running.
The buid `Dockerimage` is based on `openjdk:8-jdk-slim` which is extended by open source GraalVM `native-image.
The run `Dockerimage` is based on `scratch`, the run images are small and fast to start.

This Pull Request depends on Docker Images from the Pull Request: https://github.com/fnproject/dockers/pull/15/
Question: Should I publish these images to Docker Hub or will they be created by infrastructure when the Pull Request is integrated?

Comments are welcomed.

### CODE REVIEW

**Comment by rikgibson** [comment]
I don't think this is the right way to go about this. A couple of points:

1) The Java FDK now takes responsibility for producing the build and run images for JVM-based languages, so consider moving your image build out of fnproject/dockers into fnproject/fdk-java

2) I don't think SVM is really a valid runtime type - it's a VM choice that should be open to people building using any JVM-based language and probably should simply be a value option for the `run_image` in the func.yaml.

3) More strategically, these options should be folded into the proposal detailed in #356 - @mjg123 - such that variations in boilerplate for SVM should be dealt with there.

**Comment by delabassee** [comment]
Unless I'm wrong SVM is still based on SE8 so we probably want to keep Java and SVM separate.

**Comment by tzezula** [comment]
@rikgibson :

1. OK, I will move the Dockerfiles

2. Yes, I agree that the `native-image` can be used by any JVM based language.  But the `run_image` currently cannot be used. The problem is that jar files in `/function/app/` are not enough for the `native-image`. It also requires reflection configuration file which is user edited.
I am working on removing the need for it for FnProject entry point and Jackson reflection but it
maybe still needed for user code or external libraries.

3. Agree, making the `CLI` pluggable not to require the changes in CLI would be great.
Any estimate for the #356 PR.

**Comment by rikgibson** [comment]
This should update to be in line with 
https://github.com/fnproject/cli/pull/369 when it's eventually done.

**Comment by tzezula** [comment]
I've rewritten the feature on top of `fn init --init-image`.
This PR is no more needed.

**Pull request closed without merging**
