### PR TITLE
Extend homebrew command

### PR DESCRIPTION
**Pull request by denismakogon**
The CLI has a pretty high release flow (each commit triggers a release), so, we need to recommend people to update homebrew repository info.

Closes: #549

### CODE REVIEW

**Comment by carimura** [comment]
LGTM but not sure it should close #549 (if you want added to docs also)

**Comment by denismakogon** [comment]
@carimura let me explain it, initially, we thought (me and @devcamcar) that homebrew Fn releases were outdated since 0.5.45, but it appeared that homebrew FN releases are fine just one minor version behind.
So, we can't blame homebrew for being late, because it's almost the same for every piece of software that is stored in public repositories if your package management tool has an old (stored locally) package references - please update it <--- that's what happened to @devcamcar.

In terms of the release schedule, one minor version delay is not critical, that's why I think this PR closes #549 (Fn CLI releases already automated but slightly outdated). As far as I understand, we have zero control over the pace of the homebrew package index update.

**Comment by denismakogon** [comment]
let's open separate tickets within the corresponding repos (docs, tutorials).

**Comment by denismakogon** [comment]
@carimura leaving big green "merge" button for you. :click-click-click:

**Comment by devcamcar** [comment]
Also, for the record, they did just update the Fn homebrew formula 2 days ago, but it should be automated.  It's only being updated at random intervals, usually 1-3 months.

https://github.com/Homebrew/homebrew-core/commits/master/Formula/fn.rb

**Comment by carimura** [comment]
@denismakogon can you please make sure a new ticket (or PR) is created for updating docs before closing #549? That's my point. I don't want to drop the hand off when follow ups are needed. thanks.

And ya there's a pretty big gap in versions on brew causing big delays.

**Pull request merged**
