### PR TITLE
Hides docker build unless error, shows dots instead.

### PR DESCRIPTION
**Pull request by treeder**
dec-11-2017 16-30-53

Or when error occurs:
dec-11-2017 16-39-52

### CODE REVIEW

**Comment by rdallman** [comment]
fwiw i never minded the docker output even for succeeding builds, at a minimum because sometimes i'm on a not so hot network and the build step is stuck yanking down some gigantic base image to use or doing some gigantic apt-get install and i'm just curious what it's stuck on. with this, in that case since it's buffering the output until there's an error, i'll never know where it got stuck when i give up after 20 minutes, throw my computer across the room, and mumble vulgar words about whales. not sure of the benefits here other than simple noise reduction and possibly hiding that we use docker, but idk, pros > cons to me I think to just show it. `fn deploy` is noisy, yea, but when that output is useful, it's useful, and ctrl+k makes the bad man go away easily enough.

**Comment by carimura** [comment]
@rdallman agreed, think we could simply add a -v for verbose mode for those that want to peek behind curtain.

**Comment by treeder** [comment]
Mostly just because the docker build output is so lengthy. And it's a little bit startling on first go as it  makes up 99% of all the output. For example:

Old:
screen shot 2017-12-11 at 11 44 03 pm

New:
screen shot 2017-12-11 at 11 44 15 pm

**Comment by treeder** [comment]
Added a global `--log-level` flag for any command to use, but any command that builds the container will not support this. See images in previous comment for example using this flag.

**Comment by treeder** [comment]
Also, if there's an error it will show this:

screen shot 2017-12-11 at 11 47 06 pm

**Comment by treeder** [comment]
BTW, could have verbose too (which would just be log-level=debug), just using log-level to be consistent with other things. Also more flexible since someone may want log-level fatal or something (ie: no output).

**Comment by rdallman** [comment]
linking for relevance https://github.com/fnproject/cli/issues/5 (oldie but goodie)

**Comment by rdallman** [comment]
verbose mode seems like a fine compromise. fwiw heroku's cli is super duper noisy by default and i think most people find it a nice experience

**Comment by treeder** [comment]
@rdallman --log-level work for you?

**Comment by rdallman** [comment]
seems more like a server-side config, also have to type `-log-level=debug` which isn't perfectly intuitive. `-v` and `-vv` [and even `-vvv`] are pretty standard CLI syntax for verbose mode.

**Comment by treeder** [comment]
Ok, will add -v

**Comment by treeder** [comment]
Changed to --verbose and -v.

NOTE: this overrides the `-v` for version now.

**Pull request merged**
