### PR TITLE
Restructure CLI README Page

### PR DESCRIPTION
**Pull request by michael-w-williams**
Restructuring CLI README for general and dev information.

### CODE REVIEW

**Comment by carimura** [comment]
i'd personally like to stick with brew as mac primary as long as we get #549 finished in a reasonable amount of time.

rest of the changes are easy.

**Comment by michael-w-williams** [comment]
Bump. I need a review to merge. thanks.

**Comment by carimura** [comment]
Can we revert the brew install back to primary?

**Comment by michael-w-williams** [comment]
I'll swap em.

**Comment by michael-w-williams** [comment]
Updated.

**Comment by michael-w-williams** [comment]
Updated.

**Pull request merged**
