### PR TITLE
Missing oci config fix

### PR DESCRIPTION
**Pull request by JadeRedworth**
There is a current bug if the ‘.oci/config’ file is missing. 

I have added a check to ensure it is there before the values are gathered.

### CODE REVIEW

**Comment by msgodf** [comment]
Worked for me! Just to clarify:  it takes values from `~/.oci/config` *then* the context file?

**Comment by msgodf** [comment]
What I mean by this is an error that says something like

Unable to find tenancyID in configuration: oracle.tenancy-id is missing from current-context file and tenancy-id wasn't found in `~/.oci/config`.

**Comment by msgodf** [comment]
And so on for each missing value...

**Comment by JadeRedworth** [comment]
Yes, the context file should override the config file. I'll change the errors now.

**Comment by msgodf** [comment]
Great, that makes it clearer!

**Pull request merged**
