### PR TITLE
Optionally fixate build and runtime images in func.yaml on init 

### PR DESCRIPTION
**Pull request by zootalures**
Reason for PR: 

Fn builds are generally unpredictable as they depend on :latest images for build and run in most cases. 

If a language binding supports working out specific tags for build and run  then let it set that in build_image and runtime_image on fn init.

### CODE REVIEW

**Comment by shaunsmith** [comment]
I don't see any docs updated to describe the changes in PR #108?  What are the semantics and how is it used? It looks like FN_JAVA_FDK_VERSION can be used for configuration but I grepped for references and didn’t find any other than in java.go.

**Comment by zootalures** [comment]
Yep we've had this behaviour for a few months (it just works a bit diferently now)  but you are right tht docs are missing - any thoughts  is a the right place to doc this?  (it's a CLI feature but specific to java?)

**Comment by zootalures** [comment]
Thinking about it  - if the other FDKs were added on FN init (they need to be) then this is a generic param

**Comment by shaunsmith** [comment]
True, FN_FDK_VERSION could be enough?

**Pull request merged**
