### PR TITLE
updates to contrib

### PR DESCRIPTION
**Pull request by rdallman**
tiny follow ups to #189

### CODE REVIEW

**Comment by treeder** [comment]
I think developers should go the `git clone` route so they know what's going on. The reason for this in the first place was to help people that aren't familiar with Go and this change doesn't help with that. eg: Where the hell did `go get` put this stuff?

**Comment by rdallman** [comment]
i'll acquiesce - I will reduce it to checking out of `github.com/fnproject/fn` instead of giving the option for a fork build. multiple examples from other people with more stars than us: https://github.com/kubernetes/kubernetes https://github.com/gin-gonic/gin https://github.com/gohugoio/hugo https://github.com/coreos/etcd/blob/master/Documentation/dl_build.md#build-the-latest-version

**Comment by rdallman** [comment]
updated https://github.com/fnproject/cli/pull/190/commits/9e6822ab44cde1af69d3767c9fcc99a54beac52d @treeder

**Comment by crush-157** [comment]
@rdallman the reason I included the checking out from a fork is because that's what someone external to the core team who wants to contribute (like me) is going to do most of the time.

**Comment by rdallman** [comment]
> @rdallman the reason I included the checking out from a fork is because that's what someone external to the core team who wants to contribute (like me) is going to do most of the time.

Yep, it is a problem. I guess my hope is that we can steer people towards:

* clone `fnproject`'s repo
* add forked repo as a remote

I reviewed a number of go projects https://github.com/fnproject/cli/pull/190#issuecomment-370591994 and none of them explicitly mention pushing to a fork branch to submit a PR in their 'get the code and build it' step -- I do agree it seems nice not to muddle these two. If we recommend to get the code by cloning to the proper location it will avoid build errors (as experienced), at least, and then it's easy to go from there to contribute rather than having to move things around :)

there are, of course, likely a number of ways to accomplish this.

**Comment by treeder** [comment]
Cloning then adding remote makes the most sense. Which maybe makes the `go get` way easier... :) 

Also, I didn't notice the follow up that already had the person cd'ing into the right dir, was just looking at the changes instead of the full file (my bad), so if you want to go back to `go get`, go for it.

**Comment by rdallman** [comment]
> Also, I didn't notice the follow up that already had the person cd'ing into the right dir, was just looking at the changes instead of the full file (my bad), so if you want to go back to go get, go for it.

there seems to be a mix among the community. since the cli is not build-able without `make dep`, clone might make more sense, since `go get` makes some installation assumptions.

**Pull request merged**
