### PR TITLE
Fix fn build output in case of "verbose" flag

### PR DESCRIPTION
**Pull request by denismakogon**

### CODE REVIEW

**Comment by denismakogon** [comment]
Here's some testing results for this:
with `-verbose`
```
fn build -verbose
Building image fnproject/test-fdk-python:0.0.6 
Sending build context to Docker daemon  24.06kB
Step 1/7 : FROM python:3.6.2
 ---> 26acbad26a2c
Step 2/7 : RUN mkdir /code
 ---> Using cache
 ---> 647d001c756c
Step 3/7 : ADD . /code/
 ---> Using cache
 ---> e9577fa44da7
Step 4/7 : WORKDIR /code/
 ---> Using cache
 ---> aa5aef7fe939
Step 5/7 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> f188ee68d643
Step 6/7 : WORKDIR /code/
 ---> Using cache
 ---> 9cc0585af971
Step 7/7 : ENTRYPOINT python3 func.py
 ---> Using cache
 ---> 355960c9d61d
Successfully built 355960c9d61d
Successfully tagged fnproject/test-fdk-python:0.0.6

Function fnproject/test-fdk-python:0.0.6 built successfully.

```
without `-verbose`
```
fn build
Building image fnproject/test-fdk-python:0.0.6 
Function fnproject/test-fdk-python:0.0.6 built successfully.
```

**Comment by eshneken** [comment]
Denis -- Did you also update the help readme to specify "-verbose" instead of "-v" or "--verbose"?

eshneken@eshneken-mbp:~/Workspaces/fn$ fn build -help
NAME:
   fn build - build function version

USAGE:
   fn build [command options] [arguments...]

OPTIONS:
   -v          verbose mode
   --no-cache  Don't use docker cache

**Comment by denismakogon** [comment]
it doesn't seem like you've built it from source, so you are running an older version of CLI, helper readme would change (see `make build`).
My helper looks like:
```
fn build -help
NAME:
   fn build - build function version

USAGE:
   fn build [command options] [arguments...]

OPTIONS:
   --verbose   verbose mode
   --no-cache  Don't use docker cache
```

**Comment by eshneken** [comment]
Yes, I'm running fn 0.4.30 which is the latest version pulled by Homebrew.  Sounds like you got it all covered, thanks!

**Comment by rdallman** [comment]
why change from `-v` ? (even if it was broke, why not fix it instead of change it?) `-v` is pretty standard among utilities I've seen for verbose mode.

**Pull request closed without merging**
